### ISSUE TITLE
./configure && make issues

### ISSUE THREAD

**Issue by gediminasmargis** [Lurk/ffmpeg-php#1]
Hello,

I have tried to install this library on Centos 7 64-bit server and got this output:

In file included from /usr/include/sys/stat.h:106:0,
                 from /usr/include/php/main/php_streams.h:28,
                 from /usr/include/php/main/php.h:396,
                 from /home/gm/ffmpeg-php-code-678-trunk/ffmpeg-php/ffmpeg-php.c:40:
/usr/include/bits/stat.h:91:21: error: field 'st_atim' has incomplete type
     struct timespec st_atim;  /\* Time of last access.  _/
                     ^
/usr/include/bits/stat.h:92:21: error: field 'st_mtim' has incomplete type
     struct timespec st_mtim;  /_ Time of last modification.  _/
                     ^
/usr/include/bits/stat.h:93:21: error: field 'st_ctim' has incomplete type
     struct timespec st_ctim;  /_ Time of last status change.  _/
                     ^
/usr/include/bits/stat.h:152:21: error: field 'st_atim' has incomplete type
     struct timespec st_atim;  /_ Time of last access.  _/
                     ^
/usr/include/bits/stat.h:153:21: error: field 'st_mtim' has incomplete type
     struct timespec st_mtim;  /_ Time of last modification.  _/
                     ^
/usr/include/bits/stat.h:154:21: error: field 'st_ctim' has incomplete type
     struct timespec st_ctim;  /_ Time of last status change.  _/
                     ^
In file included from /usr/include/php/main/php_streams.h:28:0,
                 from /usr/include/php/main/php.h:396,
                 from /home/gm/ffmpeg-php-code-678-trunk/ffmpeg-php/ffmpeg-php.c:40:
/usr/include/sys/stat.h:366:31: error: array type has incomplete element type
         const struct timespec __times[2],
                               ^
/usr/include/sys/stat.h:373:54: error: array type has incomplete element type
 extern int futimens (int __fd, const struct timespec __times[2]) __THROW;
                                                      ^
In file included from /usr/include/php/main/php.h:402:0,
                 from /home/gm/ffmpeg-php-code-678-trunk/ffmpeg-php/ffmpeg-php.c:40:
/usr/include/php/TSRM/tsrm_virtual_cwd.h:218:2: error: unknown type name 'time_t'
  time_t                         expires;
  ^
/usr/include/php/TSRM/tsrm_virtual_cwd.h:246:86: error: unknown type name 'time_t'
 CWD_API realpath_cache_bucket_ realpath_cache_lookup(const char _path, int path_len, time_t t TSRMLS_DC);
                                                                                      ^
/home/gm/ffmpeg-php-code-678-trunk/ffmpeg-php/ffmpeg-php.c: In function 'zm_info_ffmpeg':
/home/gm/ffmpeg-php-code-678-trunk/ffmpeg-php/ffmpeg-php.c:194:38: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     m_codec_list[m_codec_list_len] = (char)NULL;
                                      ^
make: *_\* [ffmpeg-php.lo] Error 1

How can I fix it?

**Comment by Lurk** [comment]
Hello @t1nkerer,
 what version of php and ffmpeg installed?

**Comment by gediminasmargis** [comment]
ffmpeg -version
ffmpeg version 2.2.1
built on Jun 17 2014 01:25:46 with gcc 4.8.2 (GCC) 20140120 (Red Hat 4.8.2-16)
configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 --mandir=/usr/share/man --enable-shared --enable-runtime-cpudetect --enable-gpl --enable-version3 --enable-postproc --enable-avfilter --enable-pthreads --enable-x11grab --enable-vdpau --disable-avisynth --enable-frei0r --enable-libdc1394 --enable-libgsm --enable-libmp3lame --enable-libnut --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxavs --enable-libxvid --extra-cflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC' --disable-stripping
libavutil      52. 66.100 / 52. 66.100
libavcodec     55. 52.102 / 55. 52.102
libavformat    55. 33.100 / 55. 33.100
libavdevice    55. 10.100 / 55. 10.100
libavfilter     4.  2.100 /  4.  2.100
libswscale      2.  5.102 /  2.  5.102
libswresample   0. 18.100 /  0. 18.100
libpostproc    52.  3.100 / 52.  3.100

php --version
PHP 5.4.35 (cli) (built: Nov 14 2014 06:51:04)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

**Comment by Lurk** [comment]
@t1nkerer 
long way to solve this issue https://stackoverflow.com/a/14947692/2766252

short way: 

```
sudo mv /usr/local/include/libavutil/time.h /usr/local/include/libavutil/time.h_
make
sudo mv /usr/local/include/libavutil/time.h_ /usr/local/include/libavutil/time.h
```

**Comment by sanju9x** [comment]
install ffmpeg-php and ffmpeg on centos 7.1
https://hub.9xhost.info/knowledgebase/article/39/install-ffmpeg---php-ffmpeg-on-centos-7-1/
